package com.jsn.test;

class EnumValues {
	enum EmailCategories {
		DESK_CHANGE, CHANGE_REQUEST, DECLINE_SURVEY, ADD_FIND_SURVEY, FORWARD_SAP, FORWARD_TSC, UNDELIVERABLE, RESEARCH, QUERY, UNCLASSIFIED;
	}

	enum MerchantEmailCategories {
		DESK_CHANGE, CHANGE_REQUEST, RESEARCH, QUERY, UNDELIVERABLE, UNCLASSIFIED;
	}

	enum RCSupplierEmailCategories {
		CHANGE_REQUEST, FORWARD_SAP, RESEARCH, QUERY, UNDELIVERABLE, UNCLASSIFIED;
	}

	enum SCSupplierEmailCategories {
		CHANGE_REQUEST, DECLINE_SURVEY, ADD_FIND_SURVEY, FORWARD_SAP, FORWARD_TSC, RESEARCH, QUERY, UNDELIVERABLE, UNCLASSIFIED;
	}
}
